
import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class Bakery_LTD extends Simulation {

	val httpProtocol = http
		.baseUrl("http://192.168.99.1:8080")
		.acceptHeader("*/*")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-FI,*")
		.userAgentHeader("Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1")

	val headers_0 = Map("Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")

	val headers_1 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"Origin" -> "http://192.168.99.1:8080")

	val headers_2 = Map("Origin" -> "http://192.168.99.1:8080")

	val headers_3 = Map(
		"Content-Type" -> "application/json; charset=UTF-8",
		"Origin" -> "http://192.168.99.1:8080")



	val scn = scenario("Bakery_LTD")
		.exec(http("request_0")
			.get("/http://localhost:8080/")
			.headers(headers_0))
		.pause(459 milliseconds)
		.exec(http("request_1")
			.post("/login")
			.headers(headers_1)
			.formParam("username", "barista@vaadin.com")
			.formParam("password", "barista"))
		.exec(http("request_2")
			.post("/?v-1554117827576")
			.headers(headers_2)
			.formParam("v-browserDetails", "1")
			.formParam("theme", "apptheme")
			.formParam("v-appId", "ROOT-2521314")
			.formParam("v-sh", "2160")
			.formParam("v-sw", "3840")
			.formParam("v-cw", "400")
			.formParam("v-ch", "300")
			.formParam("v-curdate", "1554117827576")
			.formParam("v-tzo", "-180")
			.formParam("v-dstd", "60")
			.formParam("v-rtzo", "-120")
			.formParam("v-dston", "true")
			.formParam("v-vw", "400")
			.formParam("v-vh", "0")
			.formParam("v-loc", "http://192.168.99.1:8080/")
			.formParam("v-wn", "ROOT-2521314-0.80821527633816")
			.formParam("v-td", "1")
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0002_response.txt"))))
		.pause(639 milliseconds)
		.exec(http("request_3")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0003_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0003_response.txt"))))
		.pause(184 milliseconds)
		.exec(http("request_4")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0004_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0004_response.txt"))))
		.pause(419 milliseconds)
		.exec(http("request_5")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0005_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0005_response.txt"))))
		.pause(238 milliseconds)
		.exec(http("request_6")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0006_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0006_response.txt"))))
		.pause(222 milliseconds)
		.exec(http("request_7")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0007_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0007_response.txt"))))
		.exec(http("request_8")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0008_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0008_response.txt"))))
		.pause(250 milliseconds)
		.exec(http("request_9")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0009_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0009_response.txt"))))
		.pause(821 milliseconds)
		.exec(http("request_10")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0010_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0010_response.txt"))))
		.pause(894 milliseconds)
		.exec(http("request_11")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0011_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0011_response.txt"))))
		.exec(http("request_12")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0012_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0012_response.txt"))))
		.exec(http("request_13")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0013_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0013_response.txt"))))
		.exec(http("request_14")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0014_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0014_response.txt"))))
		.exec(http("request_15")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0015_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0015_response.txt"))))
		.exec(http("request_16")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0016_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0016_response.txt"))))
		.exec(http("request_17")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0017_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0017_response.txt"))))
		.exec(http("request_18")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0018_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0018_response.txt"))))
		.exec(http("request_19")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0019_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0019_response.txt"))))
		.exec(http("request_20")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0020_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0020_response.txt"))))
		.exec(http("request_21")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0021_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0021_response.txt"))))
		.exec(http("request_22")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0022_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0022_response.txt"))))
		.pause(192 milliseconds)
		.exec(http("request_23")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0023_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0023_response.txt"))))
		.pause(238 milliseconds)
		.exec(http("request_24")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0024_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0024_response.txt"))))
		.pause(219 milliseconds)
		.exec(http("request_25")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0025_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0025_response.txt"))))
		.pause(178 milliseconds)
		.exec(http("request_26")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0026_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0026_response.txt"))))
		.pause(353 milliseconds)
		.exec(http("request_27")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0027_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0027_response.txt"))))
		.exec(http("request_28")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0028_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0028_response.txt"))))
		.exec(http("request_29")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0029_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0029_response.txt"))))
		.exec(http("request_30")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0030_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0030_response.txt"))))
		.exec(http("request_31")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0031_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0031_response.txt"))))
		.exec(http("request_32")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0032_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0032_response.txt"))))
		.exec(http("request_33")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0033_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0033_response.txt"))))
		.exec(http("request_34")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0034_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0034_response.txt"))))
		.exec(http("request_35")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0035_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0035_response.txt"))))
		.pause(174 milliseconds)
		.exec(http("request_36")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0036_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0036_response.txt"))))
		.pause(200 milliseconds)
		.exec(http("request_37")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0037_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0037_response.txt"))))
		.pause(159 milliseconds)
		.exec(http("request_38")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0038_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0038_response.txt"))))
		.pause(290 milliseconds)
		.exec(http("request_39")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0039_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0039_response.txt"))))
		.pause(125 milliseconds)
		.exec(http("request_40")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0040_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0040_response.txt"))))
		.pause(368 milliseconds)
		.exec(http("request_41")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0041_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0041_response.txt"))))
		.exec(http("request_42")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0042_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0042_response.txt"))))
		.exec(http("request_43")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0043_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0043_response.txt"))))
		.exec(http("request_44")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0044_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0044_response.txt"))))
		.exec(http("request_45")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0045_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0045_response.txt"))))
		.exec(http("request_46")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0046_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0046_response.txt"))))
		.exec(http("request_47")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0047_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0047_response.txt"))))
		.exec(http("request_48")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0048_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0048_response.txt"))))
		.exec(http("request_49")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0049_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0049_response.txt"))))
		.exec(http("request_50")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0050_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0050_response.txt"))))
		.exec(http("request_51")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0051_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0051_response.txt"))))
		.exec(http("request_52")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0052_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0052_response.txt"))))
		.pause(198 milliseconds)
		.exec(http("request_53")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0053_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0053_response.txt"))))
		.pause(203 milliseconds)
		.exec(http("request_54")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0054_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0054_response.txt"))))
		.pause(201 milliseconds)
		.exec(http("request_55")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0055_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0055_response.txt"))))
		.pause(274 milliseconds)
		.exec(http("request_56")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0056_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0056_response.txt"))))
		.pause(168 milliseconds)
		.exec(http("request_57")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0057_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0057_response.txt"))))
		.pause(1)
		.exec(http("request_58")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0058_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0058_response.txt"))))
		.pause(1)
		.exec(http("request_59")
			.get("/")
			.headers(headers_1)
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0059_response.txt"))))
		.exec(http("request_60")
			.post("/?v-1554117838570")
			.headers(headers_2)
			.formParam("v-browserDetails", "1")
			.formParam("theme", "apptheme")
			.formParam("v-appId", "ROOT-2521314")
			.formParam("v-sh", "2160")
			.formParam("v-sw", "3840")
			.formParam("v-cw", "400")
			.formParam("v-ch", "300")
			.formParam("v-curdate", "1554117838570")
			.formParam("v-tzo", "-180")
			.formParam("v-dstd", "60")
			.formParam("v-rtzo", "-120")
			.formParam("v-dston", "true")
			.formParam("v-vw", "400")
			.formParam("v-vh", "0")
			.formParam("v-loc", "http://192.168.99.1:8080/#!order/36798")
			.formParam("v-wn", "ROOT-2521314-0.80821527633816")
			.formParam("v-td", "1")
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0060_response.txt"))))
		.pause(217 milliseconds)
		.exec(http("request_61")
			.post("/vaadinServlet/UIDL/?v-uiId=1")
			.headers(headers_3)
			.body(RawFileBody("resources/Bakery_LTD_0061_request.txt"))
			.check(bodyBytes.is(RawFileBody("resources/Bakery_LTD_0061_response.txt"))))

	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}