import io.gatling.core.body.ElFileBody

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class Bakery_LTD extends Simulation {

	val httpProtocol = http
		.baseUrl("http://192.168.99.1:8080")
		.acceptHeader("*/*")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-FI,*")
		.userAgentHeader("Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1")

	val headers_0 = Map("Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")

	val headers_1 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"Origin" -> "http://192.168.99.1:8080")

	val headers_2 = Map("Origin" -> "http://192.168.99.1:8080")

	val headers_3 = Map(
		"Content-Type" -> "application/json; charset=UTF-8",
		"Origin" -> "http://192.168.99.1:8080")



	val initSyncAndClientIds = exec((session) => {
		session.setAll(
			"syncId" -> 0,
			"clientId" -> 0
		)
	})


	val syncIdExtract = regex("""syncId": ([0-9]*),""").saveAs("syncId")
	val clientIdExtract = regex("""clientId": ([0-9]*),""").saveAs("clientId")
	val xsrfTokenExtract = regex("""Vaadin-Security-Key\\":\\"([^\\]+)""").saveAs("seckey")


	val extract_126_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"comment.*$""").saveAs("_126_Id")
	val extract_123_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"quantity.*$""").saveAs("_123_Id")
	val extract_121_Id =  regex("""\["([0-9]*)","com.vaadin.shared.data.DataCommunicatorClientRpc""").saveAs("_121_Id")
	val extract_120_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"product.*$""").saveAs("_120_Id")
	val extract_119_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"delete.*$""").saveAs("_119_Id")
	val extract_104_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"comment.*$""").saveAs("_104_Id")
	val extract_101_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"quantity.*$""").saveAs("_101_Id")
	val extract_99_Id =  regex("""\["([0-9]*)","com.vaadin.shared.data.DataCommunicatorClientRpc""").saveAs("_99_Id")
	val extract_98_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"product.*$""").saveAs("_98_Id")
	val extract_87_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"product.*$""").saveAs("_87_Id")
	val extract_82_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"ok.*$""").saveAs("_82_Id")
	val extract_72_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"addItems.*$""").saveAs("_72_Id")
	val extract_69_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"details.*$""").saveAs("_69_Id")
	val extract_68_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"phone.*$""").saveAs("_68_Id")
	val extract_67_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"fullName.*$""").saveAs("_67_Id")
	val extract_64_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"pickupLocation.*$""").saveAs("_64_Id")
	val extract_60_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"dueTime.*$""").saveAs("_60_Id")
	val extract_59_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"dueDate.*$""").saveAs("_59_Id")
	val extract_93_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"comment.*$""").saveAs("_93_Id")
	val extract_90_Id = regex("""^.*,"([0-9]*)":\{.{0,250}"id":"quantity.*$""").saveAs("_90_Id")
	val extract_88_Id =  regex("""\["([0-9]*)","com.vaadin.shared.data.DataCommunicatorClientRpc""").saveAs("_88_Id")
	val extract_42_Id =  regex("""\[\\"([0-9]*)\\",\\"com.vaadin.shared.data.DataCommunicatorClientRpc""").saveAs("_42_Id")
	val extract_40_Id = regex("""^.*,\\"([0-9]*)\\":\{.{0,250}"id\\":\\"newOrder.*$""").saveAs("_40_Id")


	val scn = scenario("Bakery_LTD")
		.exec(initSyncAndClientIds)
		.pause(1, 5)
		.exec(http("request_0")
			.get("/http://localhost:8080/")
			.headers(headers_0))
		.pause(459 milliseconds)
		.pause(1, 5)
		.exec(http("request_1")
			.post("/login")
			.headers(headers_1)
			.formParam("username", "barista@vaadin.com")
			.formParam("password", "barista"))
		.pause(1, 5)
		.exec(http("request_2")
			.post("/?v-1554117827576")
			.headers(headers_2)
			.formParam("v-browserDetails", "1")
			.formParam("theme", "apptheme")
			.formParam("v-appId", "ROOT-2521314")
			.formParam("v-sh", "2160")
			.formParam("v-sw", "3840")
			.formParam("v-cw", "400")
			.formParam("v-ch", "300")
			.formParam("v-curdate", "1554117827576")
			.formParam("v-tzo", "-180")
			.formParam("v-dstd", "60")
			.formParam("v-rtzo", "-120")
			.formParam("v-dston", "true")
			.formParam("v-vw", "400")
			.formParam("v-vh", "0")
			.formParam("v-loc", "http://192.168.99.1:8080/")
			.formParam("v-wn", "ROOT-2521314-0.80821527633816")
			.formParam("v-td", "1")
			.check(extract_40_Id)
			.check(extract_42_Id)
			.check(xsrfTokenExtract))
		.pause(639 milliseconds)
		.pause(1, 5)
		.exec(http("request_3")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0003_request.txt"))
			)
		.pause(184 milliseconds)
		.pause(1, 5)
		.exec(http("request_4")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.check(extract_88_Id)
			.check(extract_90_Id)
			.check(extract_93_Id)
			.check(extract_59_Id)
			.check(extract_60_Id)
			.check(extract_64_Id)
			.check(extract_67_Id)
			.check(extract_68_Id)
			.check(extract_69_Id)
			.check(extract_72_Id)
			.check(extract_82_Id)
			.check(extract_87_Id)
			.body(ElFileBody("resources/Bakery_LTD_0004_request.txt"))
			)
		.pause(419 milliseconds)
		.pause(1, 5)
		.exec(http("request_5")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0005_request.txt"))
			)
		.pause(238 milliseconds)
		.pause(1, 5)
		.exec(http("request_6")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0006_request.txt"))
			)
		.pause(222 milliseconds)
		.pause(1, 5)
		.exec(http("request_7")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0007_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_8")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0008_request.txt"))
			)
		.pause(250 milliseconds)
		.pause(1, 5)
		.exec(http("request_9")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0009_request.txt"))
			)
		.pause(821 milliseconds)
		.pause(1, 5)
		.exec(http("request_10")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0010_request.txt"))
			)
		.pause(894 milliseconds)
		.pause(1, 5)
		.exec(http("request_11")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0011_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_12")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0012_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_13")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0013_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_14")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0014_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_15")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0015_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_16")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0016_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_17")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0017_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_18")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0018_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_19")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0019_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_20")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0020_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_21")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0021_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_22")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0022_request.txt"))
			)
		.pause(192 milliseconds)
		.pause(1, 5)
		.exec(http("request_23")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0023_request.txt"))
			)
		.pause(238 milliseconds)
		.pause(1, 5)
		.exec(http("request_24")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0024_request.txt"))
			)
		.pause(219 milliseconds)
		.pause(1, 5)
		.exec(http("request_25")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0025_request.txt"))
			)
		.pause(178 milliseconds)
		.pause(1, 5)
		.exec(http("request_26")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.check(extract_98_Id)
			.check(extract_99_Id)
			.check(extract_101_Id)
			.check(extract_104_Id)
			.body(ElFileBody("resources/Bakery_LTD_0026_request.txt"))
			)
		.pause(353 milliseconds)
		.pause(1, 5)
		.exec(http("request_27")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0027_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_28")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0028_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_29")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0029_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_30")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0030_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_31")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0031_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_32")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0032_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_33")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0033_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_34")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0034_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_35")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0035_request.txt"))
			)
		.pause(174 milliseconds)
		.pause(1, 5)
		.exec(http("request_36")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0036_request.txt"))
			)
		.pause(200 milliseconds)
		.pause(1, 5)
		.exec(http("request_37")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0037_request.txt"))
			)
		.pause(159 milliseconds)
		.pause(1, 5)
		.exec(http("request_38")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0038_request.txt"))
			)
		.pause(290 milliseconds)
		.pause(1, 5)
		.exec(http("request_39")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0039_request.txt"))
			)
		.pause(125 milliseconds)
		.pause(1, 5)
		.exec(http("request_40")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.check(extract_119_Id)
			.check(extract_120_Id)
			.check(extract_121_Id)
			.check(extract_123_Id)
			.check(extract_126_Id)
			.body(ElFileBody("resources/Bakery_LTD_0040_request.txt"))
			)
		.pause(368 milliseconds)
		.pause(1, 5)
		.exec(http("request_41")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0041_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_42")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0042_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_43")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0043_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_44")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0044_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_45")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0045_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_46")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0046_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_47")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0047_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_48")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0048_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_49")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0049_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_50")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0050_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_51")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0051_request.txt"))
			)
		.pause(1, 5)
		.exec(http("request_52")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0052_request.txt"))
			)
		.pause(198 milliseconds)
		.pause(1, 5)
		.exec(http("request_53")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0053_request.txt"))
			)
		.pause(203 milliseconds)
		.pause(1, 5)
		.exec(http("request_54")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0054_request.txt"))
			)
		.pause(201 milliseconds)
		.pause(1, 5)
		.exec(http("request_55")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0055_request.txt"))
			)
		.pause(274 milliseconds)
		.pause(1, 5)
		.exec(http("request_56")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0056_request.txt"))
			)
		.pause(168 milliseconds)
		.pause(1, 5)
		.exec(http("request_57")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0057_request.txt"))
			)
		.pause(1)
		.pause(1, 5)
		.exec(http("request_58")
			.post("/vaadinServlet/UIDL/?v-uiId=0")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0058_request.txt"))
			)
		.pause(1)
		.pause(1, 5)
		.exec(http("request_59")
			.get("/")
			.headers(headers_1)
			)
		.pause(1, 5)
		.exec(http("request_60")
			.post("/?v-1554117838570")
			.headers(headers_2)
			.formParam("v-browserDetails", "1")
			.formParam("theme", "apptheme")
			.formParam("v-appId", "ROOT-2521314")
			.formParam("v-sh", "2160")
			.formParam("v-sw", "3840")
			.formParam("v-cw", "400")
			.formParam("v-ch", "300")
			.formParam("v-curdate", "1554117838570")
			.formParam("v-tzo", "-180")
			.formParam("v-dstd", "60")
			.formParam("v-rtzo", "-120")
			.formParam("v-dston", "true")
			.formParam("v-vw", "400")
			.formParam("v-vh", "0")
			.formParam("v-loc", "http://192.168.99.1:8080/#!order/36798")
			.formParam("v-wn", "ROOT-2521314-0.80821527633816")
			.formParam("v-td", "1")
			.check(xsrfTokenExtract))
		.pause(217 milliseconds)
		.pause(1, 5)
		.exec(http("request_61")
			.post("/vaadinServlet/UIDL/?v-uiId=1")
			.headers(headers_3)
			.check(syncIdExtract).check(clientIdExtract)
			.body(ElFileBody("resources/Bakery_LTD_0061_request.txt"))
			)

	setUp(scn.inject(rampUsers(10) during (5 seconds))).protocols(httpProtocol)
}
